// use("betcore_db");
db.apuestas.insertMany([
  {
    id_apuesta: 1001,
    codigo_ticket: "APU2024070001",
    usuario: {
      id_usuario: 501,
      nombre_completo: "Juan Carlos Mendoza Peña",
      tipo_documento: "DNI",
      numero_documento: "12345678",
      correo: "juan.mendoza@email.com",
    },
    local: {
      id_local: 15,
      nombre_local: "Casa de Apuestas Central",
      distrito: "San Isidro",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Fútbol",
        evento: "Perú vs Chile - Eliminatorias 2026",
        mercado: "Ganador del Partido",
        opcion: "Perú",
        cuota: 2.45,
        resultado: "PENDIENTE",
      },
      {
        deporte: "Tenis",
        evento: "Wimbledon - Final Masculina",
        mercado: "Ganador",
        opcion: "Jannik Sinner",
        cuota: 1.95,
        resultado: "ACERTADO",
      },
      {
        deporte: "Baloncesto",
        evento: "NBA - Lakers vs Celtics",
        mercado: "Over/Under Total Puntos",
        opcion: "Over 215",
        cuota: 1.8,
        resultado: "PENDIENTE",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 150.5,
    monto_ganancia: 387.45,
    estado_apuesta: "PENDIENTE",
    fecha_apuesta: new Date("2024-07-01T10:30:00Z"),
    created_at: new Date("2024-07-01T10:30:00Z"),
    updated_at: new Date(),
    fuente: "Presencial",
  },
  {
    id_apuesta: 1002,
    codigo_ticket: "APU2024070002",
    usuario: {
      id_usuario: 502,
      nombre_completo: "María Fernanda Torres Ríos",
      tipo_documento: "DNI",
      numero_documento: "23456789",
      correo: "maria.torres@email.com",
    },
    local: {
      id_local: 16,
      nombre_local: "ControlBet Miraflores",
      distrito: "Miraflores",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Fútbol",
        evento: "Alianza Lima vs Sporting Cristal",
        mercado: "Doble oportunidad",
        opcion: "Alianza Lima o empate",
        cuota: 1.6,
        resultado: "PENDIENTE",
      },
      {
        deporte: "Vóley",
        evento: "Perú vs Argentina",
        mercado: "Ganador del Partido",
        opcion: "Perú",
        cuota: 2.1,
        resultado: "PENDIENTE",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 80.0,
    monto_ganancia: 0.0,
    estado_apuesta: "PENDIENTE",
    fecha_apuesta: new Date("2024-07-02T11:30:00Z"),
    created_at: new Date("2024-07-02T11:30:00Z"),
    updated_at: new Date(),
    fuente: "Web",
  },
  {
    id_apuesta: 1003,
    codigo_ticket: "APU2024070003",
    usuario: {
      id_usuario: 503,
      nombre_completo: "Luis Alberto Quispe Vargas",
      tipo_documento: "DNI",
      numero_documento: "34567890",
      correo: "luis.quispe@email.com",
    },
    local: {
      id_local: 17,
      nombre_local: "BetCore Norte",
      distrito: "Los Olivos",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Fútbol",
        evento: "Universitario vs Melgar",
        mercado: "Ganador del Partido",
        opcion: "Universitario",
        cuota: 1.85,
        resultado: "ACERTADO",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 120.0,
    monto_ganancia: 222.0,
    estado_apuesta: "GANADA",
    fecha_apuesta: new Date("2024-07-03T12:30:00Z"),
    created_at: new Date("2024-07-03T12:30:00Z"),
    updated_at: new Date(),
    fuente: "App móvil",
  },
  {
    id_apuesta: 1004,
    codigo_ticket: "APU2024070004",
    usuario: {
      id_usuario: 504,
      nombre_completo: "Andrea Milagros Salazar León",
      tipo_documento: "DNI",
      numero_documento: "45678901",
      correo: "andrea.salazar@email.com",
    },
    local: {
      id_local: 18,
      nombre_local: "Apuestas Express Sur",
      distrito: "Chorrillos",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Tenis",
        evento: "Roland Garros - Semifinal",
        mercado: "Total de sets",
        opcion: "Más de 3.5 sets",
        cuota: 1.75,
        resultado: "FALLADO",
      },
      {
        deporte: "Fútbol",
        evento: "Brasil vs Uruguay",
        mercado: "Ambos anotan",
        opcion: "Sí",
        cuota: 1.9,
        resultado: "ACERTADO",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 95.75,
    monto_ganancia: 0.0,
    estado_apuesta: "PERDIDA",
    fecha_apuesta: new Date("2024-07-04T13:30:00Z"),
    created_at: new Date("2024-07-04T13:30:00Z"),
    updated_at: new Date(),
    fuente: "Presencial",
  },
  {
    id_apuesta: 1005,
    codigo_ticket: "APU2024070005",
    usuario: {
      id_usuario: 505,
      nombre_completo: "Carlos Eduardo Ramírez Soto",
      tipo_documento: "DNI",
      numero_documento: "56789012",
      correo: "carlos.ramirez@email.com",
    },
    local: {
      id_local: 19,
      nombre_local: "ControlBet Arequipa",
      distrito: "Cercado",
      ciudad: "Arequipa",
    },
    selecciones: [
      {
        deporte: "Baloncesto",
        evento: "NBA - Warriors vs Nuggets",
        mercado: "Ganador",
        opcion: "Warriors",
        cuota: 2.2,
        resultado: "PENDIENTE",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 60.0,
    monto_ganancia: 0.0,
    estado_apuesta: "PENDIENTE",
    fecha_apuesta: new Date("2024-07-05T14:30:00Z"),
    created_at: new Date("2024-07-05T14:30:00Z"),
    updated_at: new Date(),
    fuente: "Web",
  },
  {
    id_apuesta: 1006,
    codigo_ticket: "APU2024070006",
    usuario: {
      id_usuario: 506,
      nombre_completo: "Valeria Nicole Herrera Díaz",
      tipo_documento: "DNI",
      numero_documento: "67890123",
      correo: "valeria.herrera@email.com",
    },
    local: {
      id_local: 15,
      nombre_local: "Casa de Apuestas Central",
      distrito: "San Isidro",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Fútbol",
        evento: "Real Madrid vs Barcelona",
        mercado: "Ganador del Partido",
        opcion: "Real Madrid",
        cuota: 2.05,
        resultado: "PENDIENTE",
      },
      {
        deporte: "Fútbol",
        evento: "Manchester City vs Liverpool",
        mercado: "Total goles",
        opcion: "Más de 2.5",
        cuota: 1.7,
        resultado: "PENDIENTE",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 200.0,
    monto_ganancia: 0.0,
    estado_apuesta: "PENDIENTE",
    fecha_apuesta: new Date("2024-07-06T15:30:00Z"),
    created_at: new Date("2024-07-06T15:30:00Z"),
    updated_at: new Date(),
    fuente: "App móvil",
  },
  {
    id_apuesta: 1007,
    codigo_ticket: "APU2024070007",
    usuario: {
      id_usuario: 507,
      nombre_completo: "José Antonio Rojas Campos",
      tipo_documento: "DNI",
      numero_documento: "78901234",
      correo: "jose.rojas@email.com",
    },
    local: {
      id_local: 16,
      nombre_local: "ControlBet Miraflores",
      distrito: "Miraflores",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Boxeo",
        evento: "Pelea Internacional - Peso Ligero",
        mercado: "Ganador",
        opcion: "Boxeador A",
        cuota: 1.65,
        resultado: "ACERTADO",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 50.0,
    monto_ganancia: 82.5,
    estado_apuesta: "GANADA",
    fecha_apuesta: new Date("2024-07-07T16:30:00Z"),
    created_at: new Date("2024-07-07T16:30:00Z"),
    updated_at: new Date(),
    fuente: "Presencial",
  },
  {
    id_apuesta: 1008,
    codigo_ticket: "APU2024070008",
    usuario: {
      id_usuario: 508,
      nombre_completo: "Lucía Gabriela Castillo Ruiz",
      tipo_documento: "DNI",
      numero_documento: "89012345",
      correo: "lucia.castillo@email.com",
    },
    local: {
      id_local: 17,
      nombre_local: "BetCore Norte",
      distrito: "Los Olivos",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Fútbol",
        evento: "Argentina vs Colombia",
        mercado: "Resultado exacto",
        opcion: "2-1",
        cuota: 7.5,
        resultado: "PENDIENTE",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 35.0,
    monto_ganancia: 0.0,
    estado_apuesta: "PENDIENTE",
    fecha_apuesta: new Date("2024-07-08T17:30:00Z"),
    created_at: new Date("2024-07-08T17:30:00Z"),
    updated_at: new Date(),
    fuente: "Web",
  },
  {
    id_apuesta: 1009,
    codigo_ticket: "APU2024070009",
    usuario: {
      id_usuario: 509,
      nombre_completo: "Miguel Ángel Paredes Luna",
      tipo_documento: "DNI",
      numero_documento: "90123456",
      correo: "miguel.paredes@email.com",
    },
    local: {
      id_local: 18,
      nombre_local: "Apuestas Express Sur",
      distrito: "Chorrillos",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Tenis",
        evento: "US Open - Cuartos de Final",
        mercado: "Ganador",
        opcion: "Carlos Alcaraz",
        cuota: 1.55,
        resultado: "ACERTADO",
      },
      {
        deporte: "Baloncesto",
        evento: "NBA - Heat vs Bulls",
        mercado: "Ganador",
        opcion: "Heat",
        cuota: 1.88,
        resultado: "ACERTADO",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 110.25,
    monto_ganancia: 207.27,
    estado_apuesta: "GANADA",
    fecha_apuesta: new Date("2024-07-09T18:30:00Z"),
    created_at: new Date("2024-07-09T18:30:00Z"),
    updated_at: new Date(),
    fuente: "App móvil",
  },
  {
    id_apuesta: 1010,
    codigo_ticket: "APU2024070010",
    usuario: {
      id_usuario: 510,
      nombre_completo: "Camila Alejandra Flores Vega",
      tipo_documento: "DNI",
      numero_documento: "11223344",
      correo: "camila.flores@email.com",
    },
    local: {
      id_local: 19,
      nombre_local: "ControlBet Arequipa",
      distrito: "Cercado",
      ciudad: "Arequipa",
    },
    selecciones: [
      {
        deporte: "Fútbol",
        evento: "Atlético Madrid vs Sevilla",
        mercado: "Primera mitad",
        opcion: "Empate",
        cuota: 2.1,
        resultado: "FALLADO",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 70.0,
    monto_ganancia: 0.0,
    estado_apuesta: "PERDIDA",
    fecha_apuesta: new Date("2024-07-10T19:30:00Z"),
    created_at: new Date("2024-07-10T19:30:00Z"),
    updated_at: new Date(),
    fuente: "Presencial",
  },
  {
    id_apuesta: 1011,
    codigo_ticket: "APU2024070011",
    usuario: {
      id_usuario: 511,
      nombre_completo: "Diego Fernando Morales Cruz",
      tipo_documento: "DNI",
      numero_documento: "22334455",
      correo: "diego.morales@email.com",
    },
    local: {
      id_local: 15,
      nombre_local: "Casa de Apuestas Central",
      distrito: "San Isidro",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Fútbol",
        evento: "Bayern Múnich vs Dortmund",
        mercado: "Total goles",
        opcion: "Más de 3.5",
        cuota: 2.3,
        resultado: "PENDIENTE",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 45.5,
    monto_ganancia: 0.0,
    estado_apuesta: "PENDIENTE",
    fecha_apuesta: new Date("2024-07-11T10:30:00Z"),
    created_at: new Date("2024-07-11T10:30:00Z"),
    updated_at: new Date(),
    fuente: "Web",
  },
  {
    id_apuesta: 1012,
    codigo_ticket: "APU2024070012",
    usuario: {
      id_usuario: 512,
      nombre_completo: "Sofía Daniela Medina Ponce",
      tipo_documento: "DNI",
      numero_documento: "33445566",
      correo: "sofia.medina@email.com",
    },
    local: {
      id_local: 16,
      nombre_local: "ControlBet Miraflores",
      distrito: "Miraflores",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Vóley",
        evento: "Brasil vs Italia",
        mercado: "Ganador del Partido",
        opcion: "Brasil",
        cuota: 1.72,
        resultado: "ACERTADO",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 130.0,
    monto_ganancia: 223.6,
    estado_apuesta: "GANADA",
    fecha_apuesta: new Date("2024-07-12T11:30:00Z"),
    created_at: new Date("2024-07-12T11:30:00Z"),
    updated_at: new Date(),
    fuente: "App móvil",
  },
  {
    id_apuesta: 1013,
    codigo_ticket: "APU2024070013",
    usuario: {
      id_usuario: 513,
      nombre_completo: "Renato Alonso Núñez Prado",
      tipo_documento: "DNI",
      numero_documento: "44556677",
      correo: "renato.nunez@email.com",
    },
    local: {
      id_local: 17,
      nombre_local: "BetCore Norte",
      distrito: "Los Olivos",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Fútbol",
        evento: "PSG vs Marsella",
        mercado: "Ambos anotan",
        opcion: "Sí",
        cuota: 1.68,
        resultado: "PENDIENTE",
      },
      {
        deporte: "Tenis",
        evento: "ATP 500 - Final",
        mercado: "Ganador",
        opcion: "Daniil Medvedev",
        cuota: 2.05,
        resultado: "PENDIENTE",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 90.0,
    monto_ganancia: 0.0,
    estado_apuesta: "PENDIENTE",
    fecha_apuesta: new Date("2024-07-13T12:30:00Z"),
    created_at: new Date("2024-07-13T12:30:00Z"),
    updated_at: new Date(),
    fuente: "Presencial",
  },
  {
    id_apuesta: 1014,
    codigo_ticket: "APU2024070014",
    usuario: {
      id_usuario: 514,
      nombre_completo: "Paola Vanessa Chávez Pino",
      tipo_documento: "DNI",
      numero_documento: "55667788",
      correo: "paola.chavez@email.com",
    },
    local: {
      id_local: 18,
      nombre_local: "Apuestas Express Sur",
      distrito: "Chorrillos",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Baloncesto",
        evento: "NBA - Celtics vs Knicks",
        mercado: "Handicap",
        opcion: "Celtics -5.5",
        cuota: 1.92,
        resultado: "ACERTADO",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 160.0,
    monto_ganancia: 307.2,
    estado_apuesta: "GANADA",
    fecha_apuesta: new Date("2024-07-14T13:30:00Z"),
    created_at: new Date("2024-07-14T13:30:00Z"),
    updated_at: new Date(),
    fuente: "Web",
  },
  {
    id_apuesta: 1015,
    codigo_ticket: "APU2024070015",
    usuario: {
      id_usuario: 515,
      nombre_completo: "Fabricio José Rivera Rupay",
      tipo_documento: "DNI",
      numero_documento: "66778899",
      correo: "fabricio.rivera@email.com",
    },
    local: {
      id_local: 19,
      nombre_local: "ControlBet Arequipa",
      distrito: "Cercado",
      ciudad: "Arequipa",
    },
    selecciones: [
      {
        deporte: "Fútbol",
        evento: "Sport Boys vs Cienciano",
        mercado: "Ganador del Partido",
        opcion: "Cienciano",
        cuota: 2.6,
        resultado: "FALLADO",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 40.0,
    monto_ganancia: 0.0,
    estado_apuesta: "PERDIDA",
    fecha_apuesta: new Date("2024-07-15T14:30:00Z"),
    created_at: new Date("2024-07-15T14:30:00Z"),
    updated_at: new Date(),
    fuente: "App móvil",
  },
  {
    id_apuesta: 1016,
    codigo_ticket: "APU2024070016",
    usuario: {
      id_usuario: 516,
      nombre_completo: "Brayan Benjamin Huerta Cárdenas",
      tipo_documento: "DNI",
      numero_documento: "77889900",
      correo: "brayan.huerta@email.com",
    },
    local: {
      id_local: 15,
      nombre_local: "Casa de Apuestas Central",
      distrito: "San Isidro",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Fútbol",
        evento: "Inter vs Juventus",
        mercado: "Ganador del Partido",
        opcion: "Inter",
        cuota: 1.95,
        resultado: "ACERTADO",
      },
      {
        deporte: "Boxeo",
        evento: "Campeonato Mundial - Peso Medio",
        mercado: "Ganador",
        opcion: "Boxeador B",
        cuota: 2.25,
        resultado: "PENDIENTE",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 220.0,
    monto_ganancia: 429.0,
    estado_apuesta: "PENDIENTE",
    fecha_apuesta: new Date("2024-07-16T15:30:00Z"),
    created_at: new Date("2024-07-16T15:30:00Z"),
    updated_at: new Date(),
    fuente: "Presencial",
  },
  {
    id_apuesta: 1017,
    codigo_ticket: "APU2024070017",
    usuario: {
      id_usuario: 517,
      nombre_completo: "Giovanni Marcelo Gallegos De La Cruz",
      tipo_documento: "DNI",
      numero_documento: "88990011",
      correo: "giovanni.gallegos@email.com",
    },
    local: {
      id_local: 16,
      nombre_local: "ControlBet Miraflores",
      distrito: "Miraflores",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Tenis",
        evento: "WTA - Final",
        mercado: "Ganadora",
        opcion: "Iga Swiatek",
        cuota: 1.5,
        resultado: "ACERTADO",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 75.0,
    monto_ganancia: 112.5,
    estado_apuesta: "GANADA",
    fecha_apuesta: new Date("2024-07-17T16:30:00Z"),
    created_at: new Date("2024-07-17T16:30:00Z"),
    updated_at: new Date(),
    fuente: "Web",
  },
  {
    id_apuesta: 1018,
    codigo_ticket: "APU2024070018",
    usuario: {
      id_usuario: 518,
      nombre_completo: "Patricia Elena Córdova Sánchez",
      tipo_documento: "DNI",
      numero_documento: "99001122",
      correo: "patricia.cordova@email.com",
    },
    local: {
      id_local: 17,
      nombre_local: "BetCore Norte",
      distrito: "Los Olivos",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Fútbol",
        evento: "Ecuador vs Bolivia",
        mercado: "Ganador del Partido",
        opcion: "Ecuador",
        cuota: 1.45,
        resultado: "PENDIENTE",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 55.0,
    monto_ganancia: 0.0,
    estado_apuesta: "PENDIENTE",
    fecha_apuesta: new Date("2024-07-18T17:30:00Z"),
    created_at: new Date("2024-07-18T17:30:00Z"),
    updated_at: new Date(),
    fuente: "App móvil",
  },
  {
    id_apuesta: 1019,
    codigo_ticket: "APU2024070019",
    usuario: {
      id_usuario: 519,
      nombre_completo: "Roberto Martín Aguirre Molina",
      tipo_documento: "DNI",
      numero_documento: "10101010",
      correo: "roberto.aguirre@email.com",
    },
    local: {
      id_local: 18,
      nombre_local: "Apuestas Express Sur",
      distrito: "Chorrillos",
      ciudad: "Lima",
    },
    selecciones: [
      {
        deporte: "Baloncesto",
        evento: "NBA - Suns vs Mavericks",
        mercado: "Total puntos",
        opcion: "Under 228",
        cuota: 1.83,
        resultado: "PENDIENTE",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 100.0,
    monto_ganancia: 0.0,
    estado_apuesta: "PENDIENTE",
    fecha_apuesta: new Date("2024-07-19T18:30:00Z"),
    created_at: new Date("2024-07-19T18:30:00Z"),
    updated_at: new Date(),
    fuente: "Presencial",
  },
  {
    id_apuesta: 1020,
    codigo_ticket: "APU2024070020",
    usuario: {
      id_usuario: 520,
      nombre_completo: "Daniela Antonella Ramos Ibarra",
      tipo_documento: "DNI",
      numero_documento: "20202020",
      correo: "daniela.ramos@email.com",
    },
    local: {
      id_local: 19,
      nombre_local: "ControlBet Arequipa",
      distrito: "Cercado",
      ciudad: "Arequipa",
    },
    selecciones: [
      {
        deporte: "Fútbol",
        evento: "Portugal vs Francia",
        mercado: "Clasifica",
        opcion: "Francia",
        cuota: 1.98,
        resultado: "ACERTADO",
      },
    ],
    moneda: {
      id_moneda: 1,
      codigo: "PEN",
      simbolo: "S/",
    },
    monto_apostado: 180.0,
    monto_ganancia: 356.4,
    estado_apuesta: "GANADA",
    fecha_apuesta: new Date("2024-07-20T19:30:00Z"),
    created_at: new Date("2024-07-20T19:30:00Z"),
    updated_at: new Date(),
    fuente: "Web",
  },
]);
